# Generated by Django 3.2 on 2021-06-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='voted_by',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
